ADD 3 YAML files: what is time, repo size and chocolatine, save a progression

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,5 +1,4 @@
 name: chocolatine
-
 on:
   push:
     branches-ignore:
@@ -7,40 +6,69 @@ on:
   pull_request:
     branches-ignore:
       - ga-ignore-**
+
 env:
-  - MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-REN-2-1-bschocolatine-axel.wiemert.git
-  - EXECUTABLES: my_rpg,lem-in
+  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DOP-200-REN-2-1-bschocolatine-axel.wiemert.git"
+  EXECUTABLES: "mysh,lem-in"
 
 jobs:
   check_repository_cleaniness:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
       - run: |
-          
+          BAD_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -iname "*croissant*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov")
+          for FILES in $BAD_FILES; do
+            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
+          done
+          if [ "$BAD_FILES" != ""]; then
+            exit 1
+          fi
 
   check_program_compilation:
     needs: check_repository_cleaniness
     runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+          run: make
+        timeout-minutes: 3
+      - run: make clean
+      - run: |
+          OIFS=$IFS
+          IFS=','
+          for x in $EXECUTABLES
+            do
+              ./$x
+            done
+          IFS=$OIFS
 
   run_tests:
     needs: check_program_compilation
     runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+        run: make tests_run
+        timeout-minutes: 2
 
   push_to_mirror:
     needs: run_tests
+    if: ${{ github.event_name == 'push' }}
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: pixta-dev/repository-mirroring-action@v1
         with:
           fetch-depth: 0
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.Key }}
